name = "fastapi"
compatibility_date = "2024-04-22"

[vars]
UPSTASH_REDIS_REST_TOKEN = "AYhEASQgMjUyMDViMDktMTM4Mi00ZDg2LTliZTAtMWUwYmQ2ZThjZGFhMDYxMWNkOTJlZWZlNDE4ZWE2MjlmNTcyNWE1MWI0NTY="
UPSTASH_REDIS_REST_URL = "https://apn1-flying-anteater-34884.upstash.io"